config/routes.rb
Rails.application.routes.draw do
  resources :flats
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/flat.rb
class Flat < ApplicationRecord
  validates :name, presence: true
  validates :address, presence: true
  validates :description, presence: true
  validates :price_per_night, presence: true, numericality: { only_integer: true, greater_than_or_equal_to: 5, less_than_or_equal_to: 1000 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/flats_controller.rb
class FlatsController < ApplicationController

  before_action :set_flat, only: [:show, :edit, :update, :destroy]

  def index
    @flats = Flat.all
  end

  def show
  end

  def new
    @flat = Flat.new
  end

  def create
    @flat = Flat.new(strong_params)
    @flat.save

    redirect_to flat_path(@flat)
  end

  def edit
  end

  def update
    @flat.update(strong_params)

    redirect_to flat_path(@flat)
  end

  def destroy
    @flat.destroy
    redirect_to flats_path
  end

  private

  def set_flat
    @flat = Flat.find(params[:id])
  end

  def strong_params
    params.require(:flat).permit(:name, :description, :address, :number_of_guests, :price_per_night, :picture_url)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/flats_helper.rb
module FlatsHelper
end

app/views/flats/_form.html.erb
<%= simple_form_for(flat) do |f| %>
  <%= f.input :name %>
  <%= f.input :description %>
  <%= f.input :address %>
  <%= f.input :number_of_guests %>
  <%= f.input :price_per_night %>
  <%= f.input :picture_url %>
  <%= f.submit class:'btn btn-outline-dark'%>
<% end %>

app/views/flats/edit.html.erb
<div class="container mt-4">
  <h2>Edit a flat</h2>
  <%= render "form", flat: @flat %>
</div>

app/views/flats/index.html.erb
<div class="container mt-4">
  <h1>All our flats</h1>

  <div class="row">
    <% @flats.each do |flat| %>
      <div class="col-4 d-flex align-items-stretch">
        <div class="card my-2">
          <div class="card-image" style="background-image: url(<%= asset_path flat.picture_url %>)"></div>
          <div class="flat-content">
            <h4><%= flat.name %></h4>
            <p class="flat-description"><%= flat.description %></p>
            <div class="persons-price">
              <p><i class="fas fa-user-friends"></i> <%= flat.number_of_guests %></p>
              <p><i class="fas fa-euro-sign"></i> <%= flat.price_per_night%></p>
            </div>
          </div>
          <div class="flat-actions">
            <%= link_to 'More info', flat_path(flat), class:'text-primary' %>
            <%= link_to 'Edit', edit_flat_path(flat), class:'text-warning' %>
            <%= link_to "Delete", flat_path(flat), method: :delete, data: { confirm: "Are you sure?" }, class:'text-danger' %>
          </div>
        </div>
      </div>
    <% end %>
  </div>

</div>

app/views/flats/new.html.erb
<div class="container mt-4">
  <h2>Add a flat</h2>
  <div class="">
    <%= render "form", flat: @flat %>
  </div>
</div>

app/views/flats/show.html.erb
<div class="header-image" style="background-image: url(<%= asset_path @flat.picture_url %>)"></div>
<div class="container margin-top-negative">
  <div class="row">
    <div class="col-8">
      <div class="flat-show-card">
        <h1><%= @flat.name %></h1>
        <p><%= @flat.address %></p>
      </div>
      <div class="flat-show-card">
        <h3>A bit more about this flat...</h3>
        <p><%= @flat.description %></p>
      </div>
    </div>
    <div class="col-4">
      <div class="flat-show-card">
        <h5>Book this place!</h5>
        <form action="" class="form-group">
          <input class="form-control" type="text" placeholder="From" style="width: 100%">
          <input class="form-control" type="text" placeholder="Until" style="width: 100%">
          <input type="submit" class="btn btn-success mt-2" value="Book" style="width: 100%">
        </form>
      </div>
      <div class="flat-show-card">
        <h3>Details</h3>
        <p><i class="fas fa-user-friends"></i> <%= @flat.number_of_guests %></p>
        <p><i class="fas fa-euro-sign"></i> <%= @flat.price_per_night%></p>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsSimpleAirbnb</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <script src="https://kit.fontawesome.com/619c24582a.js" crossorigin="anonymous"></script>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
  </head>

  <body>
    <nav class="navbar-default">
      <div class="container-fluid">
        <a class="logo" href="/flats">Simple Airbnb</a>
        <a class="new-flat btn btn-outline-dark" href="/flats/new">add flat</a>
      </div>
    </nav>
    <%= yield %>
  </body>
</html>